const { AppSettingForm } = require('./app_setting_form');
const { BagItProfileForm } = require('./bagit_profile_form');
const { Choice } = require('./choice');
const { Field } = require('./field');
const { Form } = require('./form');
const { NewBagItProfileForm } = require('./new_bagit_profile_form');
const { RemoteRepositoryForm } = require('./remote_repository_form');
const { TagDefinitionForm } = require('./tag_definition_form');
const { StorageServiceForm } = require('./storage_service_form');

module.exports.AppSettingForm = AppSettingForm;
module.exports.BagItProfileForm = BagItProfileForm;
module.exports.Choice = Choice;
module.exports.Field = Field;
module.exports.Form = Form;
module.exports.NewBagItProfileForm = NewBagItProfileForm;
module.exports.RemoteRepositoryForm = RemoteRepositoryForm;
module.exports.TagDefinitionForm = TagDefinitionForm;
module.exports.StorageServiceForm = StorageServiceForm;
